config/routes.rb
Rails.application.routes.draw do

  authenticated  do
    root to: "home#index", as: 'authenticated_root'
  end

  devise_for :users
  
  root to: "home#index"

  namespace :api do
    namespace :v1 do
      resources :timesheets do
        collection do 
          post :clock_in
          post :clock_out
        end
      end
    end
  end

  get "*path", to: 'home#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timesheet.rb
# This is very basic version of Timesheet
# For more advanced version, we can add timesheet_entries table
# and create entries for timesheet
class Timesheet < ApplicationRecord
  belongs_to :user

  validates_presence_of :start_time
  validate :check_end_time

  def update_hours_worked
    self.update(hours_worked: calculate_hours_worked)
  end

  def calculate_hours_worked
    if start_time && end_time
      (end_time - start_time).seconds.in_hours.to_f.round(2)
    else
      0
    end
  end

  def hours_worked_previous_month
    user.timesheets.where(created_at: (DateTime.now.beginning_of_month - 1.month)..DateTime.now.beginning_of_month)
  end

  def check_end_time
    if self.end_time && self.end_time < self.start_time
      self.errors.add(:end_time, "can't be less than start time ")
    end
  end

  def update_end_time
    self.update(end_time: DateTime.now)
    update_hours_worked
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :timesheets, dependent: :destroy

  def current_timessheet_slot
    timesheets.where(end_time: nil).first
  end

  def create_new_timesheet
    current_timessheet_slot || self.timesheets.create(start_time: DateTime.now) 
  end
end

app/controllers/api/v1/timesheets_controller.rb
class Api::V1::TimesheetsController < ApplicationController

  before_action :set_timesheet, only: %i[ show edit update destroy ]
  before_action :check_current_timesheet, only: [:new]

  def check_current_timesheet
    if current_user.current_timessheet_slot.present?
      redirect_to timesheets_path, notice: "Please Clock out from current timesheet to create new"
    end
  end

  # GET /timesheets or /timesheets.json
  def index
    @current_timesheet = current_user.current_timessheet_slot
    @timesheets = current_user.timesheets
    render json: {timesheets: @timesheets}
    # respond_to do |format|
    #   format.json {render json: {timesheets: @timesheets}}
    #   format.html
    # end
  end

  def clock_in
    render json: {clock_in: !current_user.create_new_timesheet.errors.any? }
  end

  def clock_out
    if current_timessheet_slot = current_user.current_timessheet_slot
      render json: {clock_in: !current_timessheet_slot.update_end_time}
    else
      render json: {error: "Please check in for new timesheet!"}, status: 406  
    end
  end

  # GET /timesheets/1 or /timesheets/1.json
  def show
    render json: {timesheet: @timesheet}, status: 200  
  end

  # GET /timesheets/new
  def new
    @timesheet = Timesheet.new
  end

  # GET /timesheets/1/edit
  def edit
  end

  # POST /timesheets or /timesheets.json
  def create
    @timesheet = Timesheet.new(timesheet_params)
    @timesheet.user_id = current_user.id

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to timesheets_path, notice: "Timesheet was successfully created." }
        format.json { render :show, status: :created, location: @timesheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timesheets/1 or /timesheets/1.json
  def update
    respond_to do |format|
      if @timesheet.update(timesheet_params)
        format.html { redirect_to timesheets_path, notice: "Timesheet was successfully updated." }
        format.json { render :show, status: :ok, location: @timesheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1 or /timesheets/1.json
  def destroy
    @timesheet.destroy
    respond_to do |format|
      format.html { redirect_to timesheets_url, notice: "Timesheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timesheet
      @timesheet = current_user.timesheets.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def timesheet_params
      params.require(:timesheet).permit(:start_time, :end_time)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end

end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_timesheet, only: %i[ show edit update destroy ]
  before_action :check_current_timesheet, only: [:new]

  def check_current_timesheet
    if current_user.current_timessheet_slot.present?
      redirect_to timesheets_path, notice: "Please Clock out from current timesheet to create new"
    end
  end

  # GET /timesheets or /timesheets.json
  def index
    @current_timesheet = current_user.current_timessheet_slot
    @timesheets = current_user.timesheets
    respond_to do |format|
      format.json {render json: {timesheets: @timesheets}}
      format.html
    end
  end

  def clock_in
    render json: {clock_in: !current_user.create_new_timesheet.errors.any? }
  end

  def clock_out
    if current_timessheet_slot = current_user.current_timessheet_slot
      render json: {clock_in: !current_timessheet_slot.update_end_time}
    else
      render json: {error: "Please check in for new timesheet!"}, status: 406  
    end
  end

  # GET /timesheets/1 or /timesheets/1.json
  def show
  end

  # GET /timesheets/new
  def new
    @timesheet = Timesheet.new
  end

  # GET /timesheets/1/edit
  def edit
  end

  # POST /timesheets or /timesheets.json
  def create
    @timesheet = Timesheet.new(timesheet_params)
    @timesheet.user_id = current_user.id

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to timesheets_path, notice: "Timesheet was successfully created." }
        format.json { render :show, status: :created, location: @timesheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timesheets/1 or /timesheets/1.json
  def update
    respond_to do |format|
      if @timesheet.update(timesheet_params)
        format.html { redirect_to timesheets_path, notice: "Timesheet was successfully updated." }
        format.json { render :show, status: :ok, location: @timesheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1 or /timesheets/1.json
  def destroy
    @timesheet.destroy
    respond_to do |format|
      format.html { redirect_to timesheets_url, notice: "Timesheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timesheet
      @timesheet = current_user.timesheets.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def timesheet_params
      params.require(:timesheet).permit(:start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimesheetApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/timesheets/_form.html.erb
<%= form_with(model: timesheet) do |form| %>
  <% if timesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timesheet.errors.count, "error") %> prohibited this timesheet from being saved:</h2>

      <ul>
        <% timesheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/timesheets/edit.html.erb
<h1>Editing Timesheet</h1>

<%= render 'form', timesheet: @timesheet %>

<%= link_to 'Show', @timesheet %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/index.html.erb
<% if false %>
  <p id="notice"><%= notice %></p>

  <% if @current_timesheet %>
    <%= link_to 'Clock Out', clock_out_timesheets_path, method: :post, "data-cy" => "clock_out_link" %>
  <% else %>
    <%= link_to 'Clock In', clock_in_timesheets_path, method: :post, "data-cy" => "clock_in_link" %>
  <% end %>

  <h1>Timesheets</h1>

  <table id="timesheet_table">
    <thead>
      <tr>
        <th>Start time</th>
        <th>End time</th>
        <th>Hours worked</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @timesheets.each do |timesheet| %>
        <tr>
          <td><%= timesheet.start_time.strftime("%m-%d-%Y %H:%M") %></td>
          <td>
            <% if timesheet.end_time %>
              <%= timesheet.end_time.strftime("%m-%d-%Y %H:%M") %>
            <% end %>
          </td>
          <td><%= distance_of_time_in_words(timesheet.start_time, timesheet.end_time || DateTime.now ) %></td>
          <td><%= link_to 'Show', timesheet %></td>
          <td><%= link_to 'Edit', edit_timesheet_path(timesheet), "data-cy" => "edit_timesheet" %></td>
          <td><%= link_to 'Destroy', timesheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% end %>

app/views/timesheets/new.html.erb
<h1>New Timesheet</h1>

<%= render 'form', timesheet: @timesheet %>

<%= link_to 'Back', timesheets_path %>